In [5]:
print('This is my 1st program')
print('This is my 2nd program')
print("Now,I'll learn python")
print("Hello")

This is my 1st program
This is my 2nd program
Now,I'll learn python
Hello


# Addition

In [6]:
10 + 4

14

In [7]:
10 + 5 +6

21

In [8]:
10+2+3

15

In [9]:
10+3+78213894+235463

78449370

# Subtraction

In [12]:
10 - 4

6

In [14]:
10-4-10

-4

In [15]:
100-2332-293232

-295464

# Multiplication

In [17]:
10 * 4

40

In [18]:
10 * 4 * 5 * 6

1200

In [19]:
1000 * 2435

2435000

# Division

In [20]:
100/25

4.0

In [21]:
100.25/34

2.948529411764706

In [22]:
1010010/26523

38.08053387625834

# Exponentiation

In [23]:
2*2*2*2

16

In [24]:
2 ** 3

8

In [25]:
3 ** 2

9

In [26]:
pow(2,3)

8

In [28]:
pow(4,2)

16

# Quotient

In [31]:
10 / 3 

3.3333333333333335

In [32]:
10//3

3

In [33]:
40//7

5

In [34]:
35.5//7

5.0

In [35]:
42//7

6

In [36]:
67//11

6

# Modulus

In [37]:
10 % 3

1

In [38]:
70.75/5

14.15

In [39]:
70.75//5

14.0

In [40]:
70.755

70.755

In [41]:
# Q'No whith which we are dividing + R
68 //7

9

In [42]:
68 % 7

5

In [43]:
7*9 + 5

68

# Variabale

1. Var1 → Valid
Reason: Starts with a letter. Numbers are allowed after that.

3. Var1? → Invalid
Reason: ? is not allowed. Only letters, numbers, and _ are allowed.


5. Var1 → Valid
Reason: Starts with a letter and contains a number and _. That's okay.


7. 1Var → Invalid
Reason: Cannot start with a number. Must start with a letter or _.


9. _var → Valid
Reason: Can start with _. After that letters/numbers/_ are allowed.


11. _1var → Invalid
Reason: Starts with _ which is okay, but the rule here is inconsistent. Actually _1var IS valid in Python.
Correct Rule: Can start with _ or letter, and can contain numbers.


13. Var 1 → Valid
Reason: Wait, this is actually Invalid.  
Correct Reason: Space is not allowed in variable names.


15. .Var → Invalid
Reason: Cannot start with .. Variable names can only start with _ or A-Z or a-z.

In [1]:
# Variables are defined to store values.
# # Variables in Python can store characters, integers, boolean values etc.
# Variable name can start with only letter or '_'.
# Variable name should contains only number, letter, or '_'.

In [54]:
var = 10

In [55]:
var

10

In [59]:
Var = 20

In [60]:
Var

20

In [62]:
var_1 = 10

In [63]:
var_1

10

In [64]:
_var = 10

In [65]:
_var

10

In [67]:
_Var = 20

In [68]:
_Var

20

# Arithmetic Operation

In [44]:
x = 10
y = 12

In [45]:
x + y

22

In [46]:
x - y

-2

In [47]:
x / y 

0.8333333333333334

In [48]:
x * y

120

In [49]:
x ** y

1000000000000

In [50]:
pow(x,y)

1000000000000

In [51]:
x // y

0

In [52]:
x % y

10

# Datatype

In Python, we have 6 data types in which value for a variable is stored.

1. Integer -> 5, 10, 22, 22, 36, 535, 0

2. Float -> 5.25, 3.26, 5.32

3. Complex -> 3 + 4j, 2j

4. Boolean -> True, False

5. String -> 'Hello', "Hi", "TRUE", '23.56'

6. List -> [1,2,3, 'Hello', True]

7. Tuple -> (1,2,3,'Hello',True)

8. Set -> {1,2,3,'Hello',True}

9. Dictionary -> {1:'Sam',2:'sarah'}

In [70]:
x = 10
type(x)

int

In [71]:
x = '10'
type(x)

str

In [72]:
x = 10.25
type(x)

float

In [73]:
x = True
type(x)

bool

In [75]:
x = False
type(x)

bool

In [77]:
x = 2 + 3j
type(x)

complex

In [79]:
x = [1,2,3,'Hello']
x

[1, 2, 3, 'Hello']

In [80]:
type(x)

list

In [84]:
x = (1,2,3,'Hello')
x

(1, 2, 3, 'Hello')

In [82]:
type(x)

tuple

In [85]:
x = {1,2,3,'Hello'}
x

{1, 2, 3, 'Hello'}

In [86]:
type(x)

set

In [89]:
x = {'x':'Sara','y':20}
x

{'x': 'Sara', 'y': 20}

In [90]:
type(x)

dict

# Type Casting

In [91]:
#int -> float -> string
# In Python, we can verify the type of data using type() method.
x = '12'
type(x)

str

In [92]:
y= int(x)
type(y)

int

In [94]:
int('12')

12

In [95]:
int(12)

12

In [96]:
int(12.5)

12

In [97]:
float('12')

12.0

In [98]:
float(12)

12.0

In [99]:
float(12.9)

12.9

In [100]:
str('12')

'12'

In [101]:
str(12.4)

'12.4'

In [102]:
str(18)

'18'

# User Input

In [111]:
# We can get an user input using input keyword.
# We can print anything on console using print keyword.

In [107]:
x = int(input("Enter your age:"))
x

Enter your age: 20


20

In [109]:
x = float(input("Enter your balance:"))
x

Enter your balance: 12


12.0

In [110]:
x = (input("Enter your name:"))
x

Enter your name: Zuha


'Zuha'

In [112]:
x = 25
print(x)

25


In [116]:
print('My age is:',x)

My age is: 25


# Formatting print statement

In [117]:
# We can format print statement as follows.
# Lets take an example,
# We will take Sam's Age as an input (x).
# Sam's Father is 30 years older than Sam (y).
# We need the output as "Sam is Sam's age years old and his father is Father's age years
# old".

In [120]:
x = int(input("Enter your age:"))
y = 40
print("Sam is ",x," years old and his father is ", y, " years old" )

Enter your age: 12


Sam is  12  years old and his father is  40  years old


In [121]:
print("Sam is {a} years old and his father is {b} years old".format(a = x, b = y ))

Sam is 12 years old and his father is 40 years old


In [122]:
print("Sam is {0} years old and his father is {1} years old".format(x,y ))

Sam is 12 years old and his father is 40 years old


In [125]:
print("Sam is {} years old and his father is {} years old".format(x,y))

Sam is 12 years old and his father is 40 years old


# Indentation

In [2]:
# function
# if else
# for while
# class ()

# if (x>1):
# statements
# else:
# for i in range(0,5):
# statement

x = 1
if (x>=1):
    print ("correct")

correct


In [129]:
for i in range(0,5):
    print (i)

0
1
2
3
4


# Assignment Operators

In [130]:
# Assignment Operators are used to assign a value to a variable.(= , +=, -=, /=, %=, //=, **=)

In [134]:
x = 15
x

15

In [135]:
x += 4
x

19

In [136]:
x -= 2
x

17

In [137]:
x /= 2
x

8.5

In [138]:
x %= 3
x

2.5

In [139]:
x //= 4
x

0.0

In [140]:
x **= 5
x

0.0

# Relational Operators

In [142]:
# We have following relational operators in Python.
# Relational Operator when used returns a boolean value (True, False)
# If the condition satisfies, it returns True else False. (<=, >, >=, ==, !=)

In [143]:
10 > 7

True

In [144]:
10 < 7

False

In [145]:
x= 10
y = 12
x< y

True

In [146]:
11 <= 12

True

In [147]:
13 <= 12

False

In [148]:
12 <= 12

True

In [149]:
x = 12
y = 12
x <= 12

True

In [150]:
x > y

False

In [152]:
y > x

False

In [153]:
13 > 12

True

In [154]:
14 > 12

True

In [155]:
15 > x

True

In [156]:
x > 15

False

In [157]:
x >=y

True

In [158]:
13 >=y

True

In [159]:
15 >= 13

True

In [160]:
17 >=20

False

In [161]:
y

12

In [162]:
x == y

True

In [163]:
x = 13

In [164]:
x

13

In [165]:
x == 12

False

In [166]:
x == y

False

In [167]:
13 != 12

True

In [169]:
12.25 != 12.25

False

In [170]:
12.25 != 12

True

In [171]:
x != y

True

# Logical Operators
& -> Logical AND

| -> Logical OR

Boolean (True(1), False(0))

In [172]:
10

10

In [173]:
bool(10)

True

In [174]:
bool(1)

True

In [175]:
bool(0)

False

In [176]:
bool(0.01)

True

In [177]:
bool(-13265332)

True

In [178]:
True * True

1

In [179]:
True * False

0

In [180]:
False * True

0

In [181]:
False * False

0

In [182]:
True + True

2

In [183]:
True + False

1

In [184]:
True

True

In [185]:
# And
True & True

True

In [186]:
False & True

False

In [187]:
True & False

False

In [188]:
# Or
True | True

True

In [189]:
True | False

True

In [190]:
False | True

True

In [191]:
False | False

False

In [192]:
x = 10
x< 7

False

In [193]:
(x > 5) & (x <9)

False

In [194]:
(x>5)|(x<9)

True

In [195]:
(x> 7) & (x<15)

True

In [196]:
(x> 10) &(x<16)

False

In [197]:
(x>10) | (x <16)

True

# If -Elif- Else Statement

In [200]:
x = 20
if (x>5):
    print ("x is greater than 5")

x is greater than 5


In [201]:
if (x >15):
    print ("x is greater than 15")

x is greater than 15


In [203]:
if (x >= 15):
    print ("x is greater than 15")
else:
    print (" x is lesser than 15")

x is greater than 15


In [204]:
if (x <= 5):
    print ("x is lesser than equal to 5")
elif ((x> 5) and (x < 10)):
    print ("x is between 5 and 10")
else:
    print ("x is greater than equal to 10")

x is greater than equal to 10


In [206]:
if (x <= 5):
    print (" x is lesser than equal to 5 ")
elif ((x>5) & (x < 15)):
    print(" x is between 5 and 15")
else:
    print ("x is greater than equal to 15")

x is greater than equal to 15


In [207]:
# if no. is divide by 2 it ie even
# if no. is divided 5 or 7, it can be divided
# if no. is not divided by 2 or 5 or 7 , we'Ll say it cannot be divided

In [208]:
if (x%2 == 0):
    print ("x is even ")
elif ((x%5 == 0) or (xX7 == 0) ):
    print (" x can be divided")
else:
    print ("x cannot be divided")

x is even 


# Indexing & Slicing

## list

In [255]:
# A list object is an ordered collection of one or more data items, which can be of different data type.
# Lists are mutable, i.e., they can be modified.
# Lists are defined in square brackets [ ].
# When we create a list, than each element exists at a particular position, which is called index.
# Elements in List always starts with oth index.
# The last element in List is considered as -1th index.

list1 = [ 'Sam', 'John', 'Sarah', 'Karthik']
list2 = [1,2,3,4, 'Hello', True, 'John']

In [256]:
list1

['Sam', 'John', 'Sarah', 'Karthik']

In [257]:
list2

[1, 2, 3, 4, 'Hello', True, 'John']

In [258]:
list1[0]

'Sam'

In [259]:
list1[-1]

'Karthik'

In [260]:
len(list2)

7

In [261]:
list2[len(list2)-1]

'John'

In [262]:
#If we want to slice multiple values from a list, we can use ':' operator.
list1[:]

['Sam', 'John', 'Sarah', 'Karthik']

In [263]:
list1[0:]

['Sam', 'John', 'Sarah', 'Karthik']

In [264]:
list1[1:]

['John', 'Sarah', 'Karthik']

In [265]:
# If we want to slice multiple values from a list, we can use ':' operator.
# But if we want to skip few elements, we can do so, by providing numbers to be skipped.

list1[0:4:1]

['Sam', 'John', 'Sarah', 'Karthik']

In [266]:
list1[0:4:2]

['Sam', 'Sarah']

In [267]:
list2[::3]

[1, 4, 'John']

In [268]:
list2[::-3]

['John', 4, 1]

# List Methods
list1.append(15)-. append 15 at end

list1.extend (15,16) -> Extend the list with 15,16

list1.insert(1,24) -> Insert 24 at index:1

list1.pop() -> Pop last element and return 6

list1.pop(0) -> Pop element at index:0 and return 1

list1.remove(1) -> Remove all 1 from list

list1.count(5) -> Count all 5 in list

list1.index(5) -> Find index position of first 5

list1.reverse() -> Reverse the list

list1.sort() -> Sort the list in ascending order

list1.sort(reverse = True) -> Sort the list in descending order

len(list1) -> Length of list

In [269]:
list1.append(20)
list1

['Sam', 'John', 'Sarah', 'Karthik', 20]

In [270]:
list1.append([10,13])
list1

['Sam', 'John', 'Sarah', 'Karthik', 20, [10, 13]]

In [271]:
list1.append(-60)
list1

['Sam', 'John', 'Sarah', 'Karthik', 20, [10, 13], -60]

In [272]:
list1.extend ([15,16])
list1

['Sam', 'John', 'Sarah', 'Karthik', 20, [10, 13], -60, 15, 16]

In [273]:
list1.insert(1,24)
list1

['Sam', 24, 'John', 'Sarah', 'Karthik', 20, [10, 13], -60, 15, 16]

In [274]:
list1.pop()

16

In [275]:
list1

['Sam', 24, 'John', 'Sarah', 'Karthik', 20, [10, 13], -60, 15]

In [276]:
list1.pop(0)

'Sam'

In [277]:
list1

[24, 'John', 'Sarah', 'Karthik', 20, [10, 13], -60, 15]

In [281]:
list1.remove(15) 

In [282]:
list1

[24, 'John', 'Karthik', 20, [10, 13], -60]

In [285]:
list1.count(20)

1

In [289]:
list1.index([10,13])

4

In [290]:
list1.reverse()
list1

[-60, [10, 13], 20, 'Karthik', 'John', 24]

In [294]:
x = [4,7,2,1,9,5,8,3,-1,-2,-5,-28,84]

In [295]:
x.sort(reverse = True)

In [296]:
x

[84, 9, 8, 7, 5, 4, 3, 2, 1, -1, -2, -5, -28]

In [297]:
len(list1)

6

In [298]:
len(x)

13

# String

In [299]:
# String is defined in python either by using single quotation marks or double quotation marks.
# Strings can also be defined using three double quotes.
c ="""Hello"""
a = 'Hello'
b = "Hello"

In [300]:
a

'Hello'

In [301]:
c

'Hello'

In [302]:
b

'Hello'

In [305]:
# String indexing works exactly the same way list indexing works. First character starts with oth index and last -1th.
A = "Hello World !!! "
A[10] 

'd'

In [308]:
A[-8]

'r'

In [310]:
# If we want to slice multiple characters from a string, we can use ':' operator.
A[:5]

'Hello'

In [311]:
A[:]

'Hello World !!! '

In [312]:
A[:-3]

'Hello World !'

In [317]:
A[-10:]

'World !!! '

In [320]:
# If we want to slice multiple characters from a string, we can use ':' operator.
# But if we want to skip few characters, we can do so, by providing number of characters to be skipped.

A[0:7:1]

'Hello W'

In [324]:
A[0:7:3]

'HlW'

In [323]:
A[0:6:2]

'Hlo'

In [325]:
A[-1:0:-1]

' !!! dlroW olle'

# String Methods

A.strip() -> removes whitespaces from beginning and end

B.lower() -> Returns complete string in lower case

B.upper() -> Returns complete string in upper case

B.replace('love','hate') -> Replaces love with hate

C.split() -> Splits the string into substrings by using separator

In [326]:
A =" Hello World !!! "
B = "I love Football."
C="Hello,World"

In [327]:
A.strip()

'Hello World !!!'

In [328]:
B.lower()

'i love football.'

In [329]:
B.upper()

'I LOVE FOOTBALL.'

In [330]:
B.replace('love','hate')

'I hate Football.'

In [331]:
C.split()

['Hello,World']

# In and Not In Operator

In [2]:
A = "His Marks in Physics, Chemistry, History are 50, 60, 70."
'50' in A

True

In [3]:
'History' in A

True

# Use of Backslash

In [8]:
# If we have a string:
# We can use backslash ( \) top create such string
# Similarly we can use \t for providing tabs while using print statement.
# And we can use \n for next line while using print statement

A = "He is a \"legend\" in cricket."
A

'He is a "legend" in cricket.'

In [10]:
x = "Hello\tworld"
x

'Hello\tworld'

In [11]:
print (x)

Hello	world


In [12]:
y = "Hello\nworld"
y

'Hello\nworld'

In [13]:
print (y)

Hello
world


# Loops

### For loop

In [15]:
for i in range(0,5):
    print(i)
    print("Hello")

0
Hello
1
Hello
2
Hello
3
Hello
4
Hello


In [22]:
x = 1
for i in range(0,5):
    print(x)
    print(i+4,"\n")

1
4 

1
5 

1
6 

1
7 

1
8 



# Factorial of a number

In [24]:
x=1
for i in range (1,6):
    x = x*i
print (x) 

120


In [26]:
x = 10
for i in range(0,5):
    x = x-1
    print (i,x)

0 9
1 8
2 7
3 6
4 5


In [28]:
y = int(input("Please Enter Number:"))
x = 1
for i in range(1,y+1):
    x = x*i
print(x)

Please Enter Number: 5


120


In [31]:
l1 = ['Black', 'white','blue','red']
for i in l1:
    print (i)

Black
white
blue
red


In [33]:
for i in range(0,5):
    print (l1[0])

Black
Black
Black
Black
Black


In [35]:
for i in range(0,len(l1)):
    print (l1)

['Black', 'white', 'blue', 'red']
['Black', 'white', 'blue', 'red']
['Black', 'white', 'blue', 'red']
['Black', 'white', 'blue', 'red']


In [36]:
for i in range(0,len(l1)):
    print (l1[i])

Black
white
blue
red


In [38]:
while (i < 5):
    print ('Hello')
    i=i+1

Hello
Hello


In [39]:
i = 0
while (i <5):
    print (i)
    i = i+1

0
1
2
3
4


In [41]:
i= 0
j= 0
while (i + j < 10):
    print (i,'->',j)
    i=i+1
    j=j+2

0 -> 0
1 -> 2
2 -> 4
3 -> 6


# Break Statment

In [44]:
# Whenever we want to exit the loop and does not need to iterate further, we use break keyword.

for i in range(0,10):
    if (i == 3):
        print ("i is 3")
        break
    print (i)

0
1
2
i is 3


In [50]:
l1 = [10,20,304,40,50,60]
for i in l1:
    if i == 40:
        break
    print (i)

10
20
304


In [52]:
i = 0
while (i <5):
    print (i)
    if (i == 3):
        break
    i= i+1

0
1
2
3


# Continue

In [53]:
# Whenever we want to skip any iterator in the loop, we use continue keyword. By using continue, loop will skip the statements for the iterator and move to next iterator.

for i in range(1,5):
    if i == 3:
        print ("we are printing 3")
    print (i)

1
2
we are printing 3
3
4


In [54]:
for i in range(1,5):
    if i == 3:
        print ("we are skipping 3")
        continue
    print (i)

1
2
we are skipping 3
4


In [56]:
l1 = [10,20,30,30,20,50]
for i in l1:
    if i == 30:
        print ("skipping 30")
        continue
    print (i)

10
20
skipping 30
skipping 30
20
50


In [59]:
l1 = [10,30,20,30,30,20,50]
for i in l1:
    if i == 30:
        print ("Skipping 30")
        continue 
    if i == 2 :
        print("Breaking the loop")
        break
    print (i)

10
Skipping 30
20
Skipping 30
Skipping 30
20
50


# Functions
A function is a set of statements or a piece of code grouped together to perform a specific task.

Python has numerous in-built functions like len(), abs(), max() etc and an user can also define their own function.

Function needs to be defined first before calling.

In [15]:
x = 4
x ** 2

16

In [64]:
def square(x):
    y = x ** 2
    return (y)

In [66]:
square(2)

4

In [67]:
square(10)

100

In [68]:
def cube(x):
    y = x ** 3
    return (y)

In [69]:
cube(2)

8

In [70]:
cube(8)

512

In [3]:
def addition(x,y,z):
    add = x+y+z
    print (add)

    
addition(10,20,30)

60


In [4]:
def addMul(x,y,z):
    add = x+y+z
    mul = x*y*z
    print ("Addition: ",add)
    print("Product: ",mul)


addMul(10,20,30)

Addition:  60
Product:  6000


In [9]:
def addMul(x,y,z):
    add = x+y+z
    mul = x*y*z
    a = "Addition: " ,str(add)
    b = "Product: ",str(mul)
    return([a,b])

In [10]:
addMul(10,20,30)

[('Addition: ', '60'), ('Product: ', '6000')]

In [11]:
type(addMul(10,20,30))

list

# Factorial

In [12]:
def factorial(x):
    fact = 1
    for i in range(1,x+1):
        fact = fact*i
    return(fact)

In [13]:
factorial(3)

6

In [14]:
factorial(4)

24

# Recursive Function
A recursive function is defined as a function that calls itself directly or indirectly.

Functions needs to be defined first before calling

In [16]:
# Factorial of a number

def factorial(x):
    if x == 1:
        return 1
    else:
        return x*factorial(x-1)

In [17]:
factorial(5)

120

In [18]:
factorial(6)

720

In [19]:
factorial(7)

5040

In [25]:
# Fibinacci series
# 0 1 1 2 3 5 8 13 ...

def fibonacci(x):
    if (x == 1):
        return 0
    elif (x == 2):
        return 1 
    else :
        return (fibonacci(x-1) + fibonacci(x-2))

In [26]:
fibonacci(1)

0

In [27]:
fibonacci(2)

1

In [28]:
fibonacci(3)

1

In [31]:
x = int(input("Enter No. for fibonacci series:"))
l1 = []
for i in range(1, x+1):
    l1.append(fibonacci(i))
str1 = ""
for i in l1:
    str1 = str1 +" "+ str(i)
print (str1)

Enter No. for fibonacci series: 6


 0 1 1 2 3 5


In [32]:
l1

[0, 1, 1, 2, 3, 5]

# Sets
Set is a collection of unordered data items which can be of different data types.

Sets are defined in curly brackets {}

All the elements in Set are unique

In [34]:
A = {1, 2,3,0, "Hello", True,"Sam", False}
B= {True, False, 'True','False', 1, 0, 20 ,30, 30.0, 50, 50.25, '50.25'}

In [35]:
A

{0, 1, 2, 3, 'Hello', 'Sam'}

In [36]:
B

{20, 30, 50, 50.25, '50.25', False, 'False', True, 'True'}

In [37]:
type(A)

set

In [38]:
type(B)

set

In [46]:
list1 = [1,2,3,4,4,5,5.0,6,0.6,17,17.25,18,True,False]

In [47]:
list1

[1, 2, 3, 4, 4, 5, 5.0, 6, 0.6, 17, 17.25, 18, True, False]

In [48]:
set(list1)

{False, 0.6, 1, 2, 3, 4, 5, 6, 17, 17.25, 18}

In [50]:
c = set(list1)

for i in c:
    print(i)

0.6
1
2
3
4
5
6
False
17
17.25
18


# Set Methods

thisSet.add(4) -> It will add 4 to the set -> {1,2,3,4}

thisSet.update([4,5]) -> Add multiple values to the set -> {1,2,3,4,5}

len(thisSet) -> Count no. of unique elements in Set -> 3

thisSet.remove(2) -> Will remove 2 from the set -> {1,3}

thisSet.pop() -> Will pop out any element from set -> 1

thisSet.clear() -> Delete all the element from set -> set()

In [67]:
A = {1,2,3,4,54,65,74,86,23}

In [68]:
A

{1, 2, 3, 4, 23, 54, 65, 74, 86}

In [69]:
A.add(100)

In [70]:
A

{1, 2, 3, 4, 23, 54, 65, 74, 86, 100}

In [71]:
A.update([10,20,30])

In [72]:
A

{1, 2, 3, 4, 10, 20, 23, 30, 54, 65, 74, 86, 100}

In [73]:
A.remove(65)

In [74]:
A

{1, 2, 3, 4, 10, 20, 23, 30, 54, 74, 86, 100}

In [56]:
len(A)

10

In [57]:
A.pop()

65

In [58]:
len(A)

9

In [75]:
A.clear()

In [76]:
A

set()

# Set Operations
A.union(B) -> Will return union of both sets -> {1,2,3,4,5,6,7,8}

A.intersection(B) -> Will return common elements in both sets -> {1,7}

A-B -> Will return all elements in A but not in B -> {2,3,8}

B - A -> Will return all elements in B but not in A -> {4,5,6
                                                       
A^B -> Will return all non-common elements -> {2,3,8,4,5,6}

In [59]:
A = {1,2,3,7,8}
B = {1,7,4,5,6}

A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8}

In [60]:
A.intersection(B)

{1, 7}

In [61]:
A-B

{2, 3, 8}

In [62]:
B - A

{4, 5, 6}

In [63]:
A^B

{2, 3, 4, 5, 6, 8}

# Tuples
Tuple is a collection of ordered data items which can be of different data types.

Tuples are immutable, i.e, not changeable.

Tuples are defined in parenthesis.

In [80]:
A = (1,2,3, 'Hello',True, 'Sam')
B = [1,2,3,40,25]

In [78]:
A

(1, 2, 3, 'Hello', True, 'Sam')

In [81]:
type(B)

list

In [82]:
tuple(B)

(1, 2, 3, 40, 25)

In [83]:
C = tuple(B)

In [84]:
type(C)

tuple

In [85]:
for i in C:
    print(i)

1
2
3
40
25


# Tuple Indexing
Elements in Tuple always starts with oth index.

In [86]:
tuple1 = ( 'Sam', 'John', 'Sarah', 'Karthik')

In [87]:
tuple1[-1]

'Karthik'

In [90]:
tuple1[-3] 

'John'

In [91]:
tuple1[0]

'Sam'

In [92]:
tuple1[1]

'John'

In [93]:
tuple1[3]

'Karthik'

In [94]:
len(tuple1)

4

In [97]:
tuple1[len(tuple1)-1]

'Karthik'

# Tuple Slicing
If we want to slice multiple values from a tuple, we can use ':' operator.

In [100]:
tuple1 = ('Sam', 'John', 'Sarah', 'Karthik')

tuple1[:] 

('Sam', 'John', 'Sarah', 'Karthik')

In [101]:
tuple1[0:]

('Sam', 'John', 'Sarah', 'Karthik')

In [102]:
tuple1[1:]

('John', 'Sarah', 'Karthik')

In [103]:
tuple1[1:3]

('John', 'Sarah')

In [104]:
tuple1[0:len(tuple1)]

('Sam', 'John', 'Sarah', 'Karthik')

In [105]:
tuple1[0:len(tuple1)-1]

('Sam', 'John', 'Sarah')

In [107]:
tuple1[-1:0]

()

# Skipping elements while slicing

If we want to slice multiple values from a tuple, we can use ':' operator.

But if we want to skip few elements, we can do so, by providing numbers to be skipped.

In [108]:
tuple1 = ( 'Sam', 'John', 'Sarah', 'Karthik', 'Jason', 'Matt' )

tuple1[0:6:1]

('Sam', 'John', 'Sarah', 'Karthik', 'Jason', 'Matt')

In [109]:
tuple1[0:6:2]

('Sam', 'Sarah', 'Jason')

In [110]:
tuple1[0:6:3]

('Sam', 'Karthik')

In [111]:
tuple1[0:6:4]

('Sam', 'Jason')

In [113]:
tuple1[1:6:4]

('John', 'Matt')

In [114]:
tuple1[::3]

('Sam', 'Karthik')

# Tuple Methods

len(A) -> Length of Tuple -> 6

del A -> Will delete the Tuple

A.count(20) -> Count no. of 20 in Tuple -> 2

A.index(20) -> Will return the first occurring of 20

In [119]:
A = (10,20,30,40,50,20)

len(A)

6

In [117]:
del A

In [120]:
A.count(20)

2

In [121]:
A.index(20)

1

# Dictionary
Dictionary is an unordered collection of Key and value pairs, where the keys and values can be of any datatype.

In [122]:
Student = { 'John': 75, 'Gary': 85, 'Martina': 98, 'Joseph': 99}

Student

{'John': 75, 'Gary': 85, 'Martina': 98, 'Joseph': 99}

In [123]:
type(Student)

dict

In [125]:
Student['John']

75

In [128]:
for i in Student:
    print(i)

John
Gary
Martina
Joseph


In [131]:
for i in Student:
    print(i,'->',Student[i])

John -> 75
Gary -> 85
Martina -> 98
Joseph -> 99


In [132]:
for i in Student.values():
    print(i)

75
85
98
99


In [133]:
for i in Student.items():
    print(i)

('John', 75)
('Gary', 85)
('Martina', 98)
('Joseph', 99)


In [138]:
for i,j in Student.items():
    print(i,j)

John 75
Gary 85
Martina 98
Joseph 99


In [140]:
Student = { 'Mark' : [60,65,64,63,93], 'Sarah':[82,83,84,85,87]}

Student

{'Mark': [60, 65, 64, 63, 93], 'Sarah': [82, 83, 84, 85, 87]}

In [141]:
for i in Student['Sarah']:
    print (i)

82
83
84
85
87


In [142]:
for i in Student:
    print (i, Student[i])

Mark [60, 65, 64, 63, 93]
Sarah [82, 83, 84, 85, 87]


In [144]:
for i in Student:
    for j in Student[i]:
        print (i, j)

Mark 60
Mark 65
Mark 64
Mark 63
Mark 93
Sarah 82
Sarah 83
Sarah 84
Sarah 85
Sarah 87


# Adding items to a Dictionary

In [14]:
Student = {'John':75, 'Gary':85, 'Martina': 98, 'Joseph': 99}

Student['James']=45

In [10]:
Student

{'John': 75, 'Gary': 85, 'Martina': 98, 'Joseph': 99, 'James': 45}

In [3]:
Student['Gary']=[10,20,30,40]

In [4]:
Student

{'John': 75,
 'Gary': [10, 20, 30, 40],
 'Martina': 98,
 'Joseph': 99,
 'James': 45}

# Methods of Dictionary

len(Student) -> Length of Dictionary or no. of keys -> 4

del Student -> Will delete the dictionary 

del Student[ʻJohnʼ] -> Will delete 'John' from Student -> 2

Student.pop('Gary') -> Will return values in 'Gary' and delete Gary -> 85

Student.get('Martina') -> Will return values in Martina -> 98

In [5]:
len(Student)

5

In [6]:
del Student

In [11]:
del Student['John']

In [ ]:
Student.pop('Gary')

In [12]:
Student.get('Martina')

98

In [160]:
len(Student)

3

In [163]:
Student

{'Martina': 98, 'Joseph': 99, 'James': 45}

In [15]:
len(Student['James'])

TypeError: object of type 'int' has no len()

In [180]:
for i in Student:
    print (i, len(Student[i]))

John 5
Martina 5
Karthik 5


In [174]:
Student.pop('James')

45

# Nested Dictionary

In [175]:
Student = { 'John': { 'History':85, 'Physics':98, 'Chemistry':65, 'Geography':88, 'Mathematics':50 },
'Martina': { 'History':95, 'Physics':91, 'Chemistry':94, 'Geography':88, 'Mathematics':84 },
'Karthik': { 'History':78, 'Physics':98, 'Chemistry':95, 'Geography':86, 'Mathematics':98 }}

In [177]:
Student

{'John': {'History': 85,
  'Physics': 98,
  'Chemistry': 65,
  'Geography': 88,
  'Mathematics': 50},
 'Martina': {'History': 95,
  'Physics': 91,
  'Chemistry': 94,
  'Geography': 88,
  'Mathematics': 84},
 'Karthik': {'History': 78,
  'Physics': 98,
  'Chemistry': 95,
  'Geography': 86,
  'Mathematics': 98}}

In [178]:
Student['John']

{'History': 85,
 'Physics': 98,
 'Chemistry': 65,
 'Geography': 88,
 'Mathematics': 50}

In [181]:
Student['John']['History']

85

In [183]:
for i in Student:
    print (i,"got",Student[i]['History'], "marks in History")

John got 85 marks in History
Martina got 95 marks in History
Karthik got 78 marks in History


In [188]:
for i in Student:
    print(".....")
    for j in Student[i]:
        print(j)

.....
History
Physics
Chemistry
Geography
Mathematics
.....
History
Physics
Chemistry
Geography
Mathematics
.....
History
Physics
Chemistry
Geography
Mathematics


In [189]:
Subjects = []
for j in Student['Karthik']:
    Subjects.append(j)

In [190]:
Subjects

['History', 'Physics', 'Chemistry', 'Geography', 'Mathematics']

In [195]:
for i in Subjects:
    Marks = []
    for j in Student:
        Marks.append(Student[j][i])
        print (i,max(Marks))    

History 85
History 95
History 95
Physics 98
Physics 98
Physics 98
Chemistry 65
Chemistry 94
Chemistry 95
Geography 88
Geography 88
Geography 88
Mathematics 50
Mathematics 84
Mathematics 98


In [192]:
for j in Student:
    Marks.append(Student[j][i])
    print (i,max(Marks))

Mathematics 50
Mathematics 84
Mathematics 98


# Lambda Function
A lambda function helps in creating small anonymous function.
    
It takes any number of arguments but can have only one expression.

`lambda arguments: expression`

In [198]:
# y = lambda x: x*x
#y = lambda x: "greater than 15" if x > 15 else "lesser than 15"


def square(x):
    return (x*x)

square(2)

4

In [199]:
square(4)

16

In [200]:
square_lambda = lambda x: x*x

In [201]:
square_lambda(10)

100

In [202]:
square_lambda(15)

225

In [203]:
cube = lambda x: x ** 3

In [204]:
cube(3)

27

In [205]:
cube(6)

216

In [206]:
def addition(x,y):
    add = x+y
    return(add)

In [207]:
addition(20,30)

50

In [208]:
add = lambda x,y,z: x+y+z

In [209]:
add(10,20,30)

60

In [210]:
add(20,30,40)

90

In [211]:
prod = lambda x,y: x*y

In [212]:
prod(3,4)

12

In [213]:
prod(2.5,3)

7.5

In [214]:
def Greater(x):
    if x>15:
        print ("Greater than 15")
    else:
        print ("Lesser")

In [215]:
Greater(10)

Lesser


In [217]:
Greater(16)

Greater than 15


In [218]:
Larger = lambda x: "Greater than 15" if x>15 else "Lesser"

In [219]:
Larger(10)

'Lesser'

In [220]:
Larger(20)

'Greater than 15'

In [223]:
def add(x,y):
    add = x + y
    if add > 10:
        return (True)
    else:
        return (False )

In [224]:
add(5,5)

False

In [225]:
Sumisgreaterthan10 = lambda x,y: True if x+y>10 else False

In [226]:
Sumisgreaterthan10(10,0)

False

In [227]:
Sumisgreaterthan10(10,1)

True

In [228]:
Sumisgreaterthan10(5,5)

False

In [238]:
def even(x):
    if x % 2 == 0:
        return ("even")
    else:
        return ("odd")

In [239]:
even(3)

'odd'

In [240]:
even(12)

'even'

In [244]:
odd = lambda x:'odd' if x % 2 !=0 else 'even'

In [245]:
odd(2)

'even'

In [246]:
odd(3)

'odd'

# Map Function
A Map function takes a function and iter (list/tuple) as an argument and returns a map object of all the results, which is an iterator after applying the function to all the elements in iter.

`map(fun, iter)`

In [247]:
x = [1,2,3,4,5,6]

def square(x):
    return (x ** 2)

In [248]:
y = map(square,x)
y

In [249]:
list(y)

[1, 4, 9, 16, 25, 36]

In [250]:
a = (10,20,30,40,50)

def add(x):
    return (x+100)

In [251]:
b = map(add,a)
b

In [252]:
type(b)

map

In [253]:
tuple(b)

(110, 120, 130, 140, 150)

In [254]:
x = [1,2,3,4,5,6]
y = [10,20,30,40,50,60]

def add (x,y):
    return (x+y)

In [255]:
z = map(add,x,y)
z

In [256]:
list(z)

[11, 22, 33, 44, 55, 66]

In [257]:
x = [1,2,3]
y = [10,20]

z = map(add, x,y)
z

In [258]:
list(z)

[11, 22]

In [259]:
x = [1,2,3]
y = [10,20,30,40]

z = map(add,x,y)
z

In [260]:
list(z)

[11, 22, 33]

In [262]:
x = [10,11,12,13,14,15,16]

def oddoreven(x):
    if x%2 == 0:
        return ("Even")
    else:
        return ("Odd")


y = map(oddoreven,x)
y

In [263]:
list(y)

['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even']

# Exception Handling

Whenever an error or exception occurs during code execution, python stops and throws an error message, due to which the code does not work further.

Avoiding such exceptions is known as Exception Handling.

In python , we can do it using try block

# try-except block

x is a variable which is not yet defined.

If we will try to print x, it will show an error, and code execution will stop.

Instead what we can do, we can provide x in try-except block.

In [266]:
try:
    print (x)
except :
    print ("Please define x")

[10, 11, 12, 13, 14, 15, 16]


In [268]:
x = '10.6'

try:
    y = float(x)
    print (y)
except:
    print ("Enter Number")

10.6


In [270]:
x = "Hello"

try:
    y = float(x)
    print (y)
except:
    print ("Enter Number")
finally:
    print ("Finished .... ")

Enter Number
Finished .... 


In [272]:
def age():
    try:
        x = input("Enter Age:")
        y = int(x) + 25
        print (y)
    except:
        print ("Enter Number")
        age()
    finally:
        print ("Finished")

age()

Enter Age: hello


Enter Number


Enter Age: #


Enter Number


Enter Age: 45


70
Finished
Finished
Finished


In [273]:
def age():
    try:
        x = input("Enter Age:")
        y = int(x) +25
        print (y)
    except:
        print ("Enter Number")
        age()

age()

Enter Age: 45


70


# Finally block
Finally block can be provided after try and except.
Finally block will execute no matter if try gets executed or except.

`try:
    print (x)'
except:    
    print ("x is not defined")    
finally:   
    print ("Finished ... ")`

# Name Error
Name error is an error which occurs when a variable is not defined.

`try:
    print (x)
except:
    print ("x is not defined")
finally:
    print ("Finished ... ")`

In [278]:
try:
    print (a)
except NameError:
    print ("Define a")

(10, 20, 30, 40, 50)


# Type Error
Type error is an error which occurs when two variables of different datatype perform an operation.

In [281]:
x =2
y = 'Hi'
try:
    print (x + y)
except TypeError:
    print ("Only integers allowed")
finally:
    print ("Finished ... ")

Only integers allowed
Finished ... 


# Value Error
Value error is an error which occurs when a variable receives an argument of correct type but improper value.

In [283]:
x = 'hello'
try:
    print (int(x))
except ValueError:    
    print ("Only numbers allowed")
finally:
    print ("Finished ... ")

Only numbers allowed
Finished ... 


# ZeroDivisionError
Zero Division error is an error which occurs when a number is divided by o.

In [285]:
x = 2
y = 0
try:
    print (x/y)
except ZeroDivisionError:
    print ("Division by 0 is not allowed.")
finally:
    print ("Finished ... ")    

Division by 0 is not allowed.
Finished ... 


# Raise Exception
If as a developer you want to raise exception, you can raise exception using raise keyword.

In [289]:
l1 = [1,2,3,4]
x = 4
if x not in l1:
    raise Exception("x not in List")
l1.index(x)

3

# Concatenation

In [290]:
x = 10
y = 30

x + y

40

In [292]:
# Strings
x = "This is "
y = "awesome"

x+ y

'This is awesome'

In [300]:
x = "Ronaldo"
z = "Messi"
t = "are"
y = "Great Footballers"

In [305]:
x +','+ z +' '+ t +' '+ y

'Ronaldo,Messi are Great Footballers'

In [306]:
# Lists
x = [1,2,3]
y = [4,5,6,7]

x + y

[1, 2, 3, 4, 5, 6, 7]

In [307]:
# Tuple
x = (1,2,3)
y = (4,5,6,7,8)

x + y

(1, 2, 3, 4, 5, 6, 7, 8)

# Numpy

In [309]:
list1 = [1,2,3,4]

import numpy as np
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4])

In [310]:
arr2 = np.array([2,3,4,5,6])
arr2

array([2, 3, 4, 5, 6])

# Same Datatype 

In [311]:
import numpy as np

list1 = [1,2,3,'Sam',True]
list1

[1, 2, 3, 'Sam', True]

In [312]:
arr1 = np.array(list1)
arr1

array(['1', '2', '3', 'Sam', 'True'], dtype='<U21')

In [313]:
arr2 = np.array([1,2,3.5,4,6.25])
arr2

array([1.  , 2.  , 3.5 , 4.  , 6.25])

In [314]:
arr3 = np.array([1,2,3,True])
arr3

array([1, 2, 3, 1])

In [315]:
arr4 = np.array([1,3,6,True,False])
arr4

array([1, 3, 6, 1, 0])

# Shape size dimension

In [316]:
import pandas as pd
arr1 = np. array([1])
arr1

array([1])

In [317]:
arr1.ndim

1

In [318]:
arr1. shape

(1,)

In [319]:
arr1.size

1

In [320]:
arr2 = np.array([1,2])
arr2.ndim

1

In [321]:
arr2. shape

(2,)

In [322]:
arr2.size

2

In [324]:
arr3 = np.array([1,2,3,4])
print(arr3.ndim)

1


In [325]:
print (arr3.shape)

(4,)


In [326]:
print (arr3.size)

4


In [331]:
arr4 = np.array([[1,2],[3,4]])
arr4

array([[1, 2],
       [3, 4]])

In [332]:
print(arr4.ndim)
print (arr4.shape)
print (arr4.size)

2
(2, 2)
4


In [334]:
arr5 = np.array([[1,2,3],[1,2,3]])
arr5

array([[1, 2, 3],
       [1, 2, 3]])

In [335]:
print(arr5.ndim)
print (arr5.shape)
print (arr5.size)

2
(2, 3)
6


In [336]:
arr6 = np.array( [[1], [2], [3],[4]] )
print(arr6.ndim)
print (arr6.shape)
print (arr6.size)

2
(4, 1)
4


In [337]:
arr7 = np.array( [[[1,2], [1,2],[1,2]], [[1,2],[1,2], [1,2]], [[1,2], [1,2], [1,2]], [[1,2], [1,2],[1,2]]] )
arr7

array([[[1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2]]])

In [338]:
print(arr7.ndim)
print (arr7.shape)
print (arr7.size)

3
(4, 3, 2)
24


In [340]:
arr8 = np.array([[[1], [1]], [[1], [1]], [[1], [1]],[[1], [1]], [[1], [1]], [[1], [1]],[[1], [1]], [[1], [1]], [[1], [1]],[[1], [1]], [[1], [1]], [[1], [1]]])
print(arr8.ndim)
print (arr8.shape)
print (arr8.size)

3
(12, 2, 1)
24


In [341]:
arr9 = np. array([[[[[1], [1]]], [[[1],[1]]]]])
arr9

array([[[[[1],
          [1]]],


        [[[1],
          [1]]]]])

In [342]:
print(arr9.ndim)
print (arr9.shape)
print (arr9.size)

5
(1, 2, 1, 2, 1)
4


In [347]:
arr10 = np.array( [[[[[1], [2], [3],[4]],[[5], [6], [7],[8]],[[9], [10], [11],[12]],[[13], [14], [15],[16]]]]])
print(arr10.ndim)
print (arr10.shape)
print (arr10.size)

5
(1, 1, 4, 4, 1)
16


# Finnding eLement using index
In order to access any array element by using its position is called as indexing.

We can find the element by using its index position as 1st position 

`arr = np.array([10,20,30])`

`arr[0]` -> Will return 10 as 10 is at 0th position or 0th index

`arr[2]` -> Will return 30 as 30 is at 2nd position or 2nd index

# Finding element using negative index
In order to access elements from end, we use negative indexing.

Index :- I is considered as last element of array followed by -2 as 2nd last and so on.

`arr = np.array([10,20,30])`

`arr[-1]` -> Will return 30 as 30 is at -1th position or -1th index

# Slicing elements from array
Slicing means accessing elements from one index position to another.

`arr = np.array([10,20,30,40,50,60,70])`

`10 20 30 40 50 60 70` -> `10 20 30`
 -> `30 40 50 60 70`       -> `20 30 40 50`
  

# Slicing Elements From Array
Slicing can be done as arr[start : stop] where slice begins from start index and ends at (stop-1).

`arr[start : stop]` -> Slicing can be done as arr[start : stop : step] where steps can also be added.

`arr[start : stop : step]`

If start is not provided, it will be considered as 0.

If stop is not provided it will be considered as length of array +I.

If step is not provided, it will be considered as I.

# Filtering elements using positions as list
If instead of slicing from 0-n or I-n, we want to filter elements from random positions say (1,2,4,7), we can do so by providing list of such values as argument.

`ListI = [1,2,4,7]`

`arr[List I]` -> Will filter 1,2,4,7th index element


In [357]:
import numpy as np

arr1 = np.array([10,20,30,40,50,60,70])
arr1

array([10, 20, 30, 40, 50, 60, 70])

# Indexing

In [358]:
arr1[0]

np.int64(10)

In [359]:
arr1[1]

np.int64(20)

In [360]:
arr1[4]

np.int64(50)

# Negative Indexing

In [361]:
arr1[-1]

np.int64(70)

In [362]:
arr1[-2]

np.int64(60)

In [363]:
arr1[-3]

np.int64(50)

# Slicing

In [364]:
arr1[0:1]

array([10])

In [365]:
arr1[1:3]

array([20, 30])

In [366]:
arr1[3:7]

array([40, 50, 60, 70])

In [367]:
arr1[:-1]

array([10, 20, 30, 40, 50, 60])

In [371]:
arr1[2:-5]

array([], dtype=int64)

# Slicing with steps  

In [372]:
arr1[::7]

array([10])

In [373]:
arr1[1:4:7]

array([20])

In [374]:
arr1[::1]

array([10, 20, 30, 40, 50, 60, 70])

In [375]:
arr1[::-1]

array([70, 60, 50, 40, 30, 20, 10])

In [377]:
arr1[-2::-1]

array([60, 50, 40, 30, 20, 10])

# Slicing using list as position

In [380]:
arr1

array([10, 20, 30, 40, 50, 60, 70])

In [383]:
l1 = [1,4,5]

In [384]:
arr1[l1]

array([20, 50, 60])

In [386]:
arr1[6]

np.int64(70)